import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import SummonerProfileHeader from "@/components/SummonerProfile/SummonerProfileHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${inter.className} min-h-screen`}>
        <div className="h-16">
          <SummonerProfileHeader />
        </div>
        {children}
      </body>
    </html>
  );
}
